baseurl: 
permalink: pretty
markdown: kramdown
paginate: 5
repo: maptimemadison.github.io
github_org: maptime
maptime:
  chapter: Maptime Madison
  twitter: MaptimeMadison
  #disqus: YOUR DISQUS USERNAME
