baseurl:  /madison
permalink: pretty
markdown: kramdown
paginate: 5
repo: madison
github_org: https://github.com/MaptimeMadison/madison
maptime:
  chapter: Maptime Madison
  twitter: MaptimeMadison
  #disqus: YOUR DISQUS USERNAME
